FROM python:3.13-alpine
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
USER 65534:65534
EXPOSE 9100
CMD ["uvicorn","app:app","--host","0.0.0.0","--port","9100"]
